# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# NOTE: use save! or create! in seeds so that if an issue arises it'll raise an error and stop
# NOTE2: do a destroy on all objects before creating (rake db:seed)
Character.destroy_all
Match.destroy_all
Roleplay.destroy_all

c1 = Character.create!(name: "Main Event", age: "64", height: "6'4", weight: "220 lbs", wrestling_style: "Brawler", finisher: "The American Dream")
c2 = Character.create!(name: "Made in China", age: "28", height: "6'2", weight: "228 lbs", wrestling_style: "High Flying", finisher: "Counterfeit")
c3 = Character.create!(name: "Fuerza", age: "24", height: "5'10", weight: "180 lbs", wrestling_style: "Junior Heavyweight", finisher: "Translation")
c4 = Character.create!(name: "Joe Blow", age: "34", height: "6'2", weight: "230 lbs", wrestling_style: "Spot Wrestling", finisher: "Untitled")
c5 = Character.create!(name: "Roids", age: "28", height: "6'5", weight: "252 lbs", wrestling_style: "Hardcore", finisher: "Juiced Up")
c6 = Character.create!(name: "Asylum", age: "22", height: "6'8", weight: "260 lbs", wrestling_style: "Hardcore", finisher: "A Lobotomy")

m1 = Match.create!(character1: c1, character2: c2)
m2 = Match.create!(character1: c3, character2: c4)
m3 = Match.create!(character1: c5, character2: c6)

Roleplay.create!(character: c1, match: m1, message: "Multiply your anger by about a hundred, kate, that's how much he thinks he loves you. are you feeling lucky punk i now issue a new commandment: thou shalt do the dance. are you feeling lucky punk no, this is mount everest. you should flip on the discovery channel from time to time. but i guess you can't now, being dead and all. i don't think they tried to market it to the billionaire, spelunking, base-jumping crowd. what you have to ask yourself is, do i feel lucky. well do ya' punk? rehabilitated? well, now let me see. you know, i don't have any idea what that means. boxing is about respect. getting it for yourself, and taking it away from the other guy. when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross. you see, in this world there's two kinds of people, my friend: those with loaded guns and those who dig. you dig. i now issue a new commandment: thou shalt do the dance.")
Roleplay.create!(character: c2, match: m1, message: "Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.")
Roleplay.create!(character: c1, match: m1, message: "Cities fall but they are rebuilt. heroes die but they are remembered. it only took me six days. same time it took the lord to make the world. rehabilitated? well, now let me see. you know, i don't have any idea what that means. multiply your anger by about a hundred, kate, that's how much he thinks he loves you. no, this is mount everest. you should flip on the discovery channel from time to time. but i guess you can't now, being dead and all. let me tell you something my friend. hope is a dangerous thing. hope can drive a man insane. i did the same thing to gandhi, he didn't eat for three weeks. multiply your anger by about a hundred, kate, that's how much he thinks he loves you. you measure yourself by the people who measure themselves by you. rehabilitated? well, now let me see. you know, i don't have any idea what that means. i now issue a new commandment: thou shalt do the dance. well, what is it today? more spelunking?")
Roleplay.create!(character: c3, match: m2, message: "Ding ding ding ding. Ding. Ding, ding ding ding ding. DING DING DING! Ding, ding ding, ding ding DING DING. DING. Ding, ding ding. Ding, ding ding ding. Ding. Ding ding ding ding. Ding, ding - ding ding. DING?! DING DING DING? Ding, ding ding... ding. Ding. DING. DING! ")
Roleplay.create!(character: c4, match: m2, message: "You want a guarantee, buy a toaster. rehabilitated? well, now let me see. you know, i don't have any idea what that means. when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross. the man likes to play chess; let's get him some rocks. mister wayne, if you don't want to tell me exactly what you're doing, when i'm asked, i don't have to lie. but don't think of me as an idiot. mister wayne, if you don't want to tell me exactly what you're doing, when i'm asked, i don't have to lie. but don't think of me as an idiot. don't p!ss down my back and tell me it's raining. man's gotta know his limitations. dyin' ain't much of a livin', boy. cities fall but they are rebuilt. heroes die but they are remembered. multiply your anger by about a hundred, kate, that's how much he thinks he loves you. i don't think they tried to market it to the billionaire, spelunking, base-jumping crowd.")
Roleplay.create!(character: c5, match: m3, message: "We're both adults. I can't pretend I don't know that person is you. I want there to be no confusion. I know I owe you my life. And more than that, I respect the strategy. In your position, I would have done the same. One issue, which troubles me, I don't know what happens when our three-month contract ends. You know why I do this. I want security for my family.")
Roleplay.create!(character: c6, match: m3, message: "The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.")
Roleplay.create!(character: c5, match: m3, message: "Ever notice how sometimes you come across somebody you shouldn't have f**ked with? well, i'm that guy. you want a guarantee, buy a toaster. you want a guarantee, buy a toaster. here. put that in your report! i may have found a way out of here. this is the ak-47 assault rifle, the preferred weapon of your enemy; and it makes a distinctive sound when fired at you, so remember it. what you have to ask yourself is, do i feel lucky. well do ya' punk? man's gotta know his limitations. when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross. when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross. don't p!ss down my back and tell me it's raining. don't p!ss down my back and tell me it's raining. when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross.")
Roleplay.create!(character: c6, match: m3, message: "Circumstances have taught me that a man's ethics are the only possessions he will take beyond the grave. i don't think they tried to market it to the billionaire, spelunking, base-jumping crowd. mister wayne, if you don't want to tell me exactly what you're doing, when i'm asked, i don't have to lie. but don't think of me as an idiot. bruce... i'm god. boxing is about respect. getting it for yourself, and taking it away from the other guy. you measure yourself by the people who measure themselves by you. no, this is mount everest. you should flip on the discovery channel from time to time. but i guess you can't now, being dead and all. i now issue a new commandment: thou shalt do the dance. well, what is it today? more spelunking? circumstances have taught me that a man's ethics are the only possessions he will take beyond the grave. well, what is it today? more spelunking? no, this is mount everest. you should flip on the discovery channel from time to time. but i guess you can't now, being dead and all.")